apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zl56f4t2c-go
  janus-idp.io/tekton: zl56f4t2c-go
  backstage.io/kubernetes-id: zl56f4t2c-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zl56f4t2c-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
